apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "financefeast-data-gatherer.fullname" . }}
  labels:
    {{- include "financefeast-data-gatherer.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "financefeast-data-gatherer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "financefeast-data-gatherer.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "financefeast-data-gatherer.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:          
            {{- range .Values.env }}
          - name: {{ .name }}
            value: {{ .value }}
          {{- end }}  
          volumeMounts:
            - name: data-gatherer
              mountPath: /source/models
            - name: input-data
              mountPath: /source/input_data              
      volumes:
        - name: data-gatherer
          nfs:  
            server: nas.home
            path: /nfs_share/monitor      
        - name: input-data
          nfs:  
            server: nas.home
            path: /nfs_share/monitor_input_data
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
