apiVersion: v2
kind: PersistentVolume
metadata:
  name: "{{ .Values.volumes.name }}" 
  labels:
    type: nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: "{{ .Values.volumes.path }}" 
    server: "{{ .Values.volumes.server }}" 
  persistentVolumeReclaimPolicy: Recycle
